/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/annotation_session_access": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_session_access.id"];
          created_at?: parameters["rowFilter.annotation_session_access.created_at"];
          user_id?: parameters["rowFilter.annotation_session_access.user_id"];
          session_id?: parameters["rowFilter.annotation_session_access.session_id"];
          role?: parameters["rowFilter.annotation_session_access.role"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["annotation_session_access"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** annotation_session_access */
          annotation_session_access?: definitions["annotation_session_access"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_session_access.id"];
          created_at?: parameters["rowFilter.annotation_session_access.created_at"];
          user_id?: parameters["rowFilter.annotation_session_access.user_id"];
          session_id?: parameters["rowFilter.annotation_session_access.session_id"];
          role?: parameters["rowFilter.annotation_session_access.role"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_session_access.id"];
          created_at?: parameters["rowFilter.annotation_session_access.created_at"];
          user_id?: parameters["rowFilter.annotation_session_access.user_id"];
          session_id?: parameters["rowFilter.annotation_session_access.session_id"];
          role?: parameters["rowFilter.annotation_session_access.role"];
        };
        body: {
          /** annotation_session_access */
          annotation_session_access?: definitions["annotation_session_access"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/annotation_sessions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_sessions.id"];
          created_at?: parameters["rowFilter.annotation_sessions.created_at"];
          name?: parameters["rowFilter.annotation_sessions.name"];
          views?: parameters["rowFilter.annotation_sessions.views"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["annotation_sessions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** annotation_sessions */
          annotation_sessions?: definitions["annotation_sessions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_sessions.id"];
          created_at?: parameters["rowFilter.annotation_sessions.created_at"];
          name?: parameters["rowFilter.annotation_sessions.name"];
          views?: parameters["rowFilter.annotation_sessions.views"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.annotation_sessions.id"];
          created_at?: parameters["rowFilter.annotation_sessions.created_at"];
          name?: parameters["rowFilter.annotation_sessions.name"];
          views?: parameters["rowFilter.annotation_sessions.views"];
        };
        body: {
          /** annotation_sessions */
          annotation_sessions?: definitions["annotation_sessions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  annotation_session_access: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at: string;
    /** Format: character varying */
    user_id: string;
    /** Format: character varying */
    session_id: string;
    /** Format: character varying */
    role: string;
  };
  annotation_sessions: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at: string;
    /** Format: character varying */
    name: string;
    /**
     * Format: integer
     * @default 0
     */
    views: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description annotation_session_access */
  "body.annotation_session_access": definitions["annotation_session_access"];
  /** Format: integer */
  "rowFilter.annotation_session_access.id": string;
  /** Format: timestamp without time zone */
  "rowFilter.annotation_session_access.created_at": string;
  /** Format: character varying */
  "rowFilter.annotation_session_access.user_id": string;
  /** Format: character varying */
  "rowFilter.annotation_session_access.session_id": string;
  /** Format: character varying */
  "rowFilter.annotation_session_access.role": string;
  /** @description annotation_sessions */
  "body.annotation_sessions": definitions["annotation_sessions"];
  /** Format: integer */
  "rowFilter.annotation_sessions.id": string;
  /** Format: timestamp without time zone */
  "rowFilter.annotation_sessions.created_at": string;
  /** Format: character varying */
  "rowFilter.annotation_sessions.name": string;
  /** Format: integer */
  "rowFilter.annotation_sessions.views": string;
}

export interface operations {}

export interface external {}
