import Head from "next/head"
import styles from "@styles/home.module.css"
import Container from "@mui/material/Container"

function Home(): JSX.Element {
  return (
    <Container>
      <Head>
        <title>Markup Annotation Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome <a href="https://nextjs.org">Sam!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sam
        </a>
      </footer>
    </Container>
  )
}

export default Home
